# Generated by Django 2.2.4 on 2019-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(default='None', max_length=100)),
                ('name', models.CharField(default='None', max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('decs', models.TextField(default='None')),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimensionsCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Length', models.CharField(max_length=100)),
                ('Width', models.BooleanField(default=False)),
                ('Height', models.BooleanField(default=False)),
                ('Boot_Space', models.CharField(max_length=100)),
                ('Ground_Clearance', models.CharField(max_length=100)),
                ('Wheel_Base', models.CharField(max_length=100)),
                ('Front_Tread', models.CharField(max_length=100)),
                ('Rear_Tread', models.CharField(max_length=100)),
                ('Gross_Weight', models.CharField(max_length=100)),
                ('No_Doors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EngineTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('No_cylinder', models.CharField(max_length=100)),
                ('Turbo_Charger', models.BooleanField(default=False)),
                ('Super_Charge', models.BooleanField(default=False)),
                ('Gear_Box', models.CharField(max_length=100)),
                ('Drive_Type', models.CharField(max_length=100)),
                ('Tank_Capacity', models.CharField(max_length=100)),
                ('Valve_Configuration', models.CharField(max_length=100)),
                ('Fuel_Supply', models.CharField(max_length=100)),
                ('Valves_Cylinder', models.CharField(max_length=100)),
                ('Max_Torque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment_Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Cd_Player', models.BooleanField(default=False)),
                ('CD_Changer', models.BooleanField(default=False)),
                ('DVD_Player', models.BooleanField(default=False)),
                ('Radio', models.BooleanField(default=False)),
                ('No_Speakers', models.CharField(max_length=100)),
                ('Integrated_2DIN', models.BooleanField(default=False)),
                ('USB_Auxiliary_input', models.BooleanField(default=False)),
                ('Bluetooth_Connectivity', models.BooleanField(default=False)),
                ('Touch_Screen', models.BooleanField(default=False)),
                ('Internal_Storage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Top_Speed', models.CharField(max_length=100)),
                ('Turbo_Charger', models.BooleanField(default=False)),
                ('Super_Charge', models.BooleanField(default=False)),
                ('Turning_Radius', models.CharField(max_length=100)),
                ('Acceleration', models.CharField(max_length=100)),
                ('Front_Brake', models.CharField(max_length=100)),
                ('Rear_Brake', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Power_Steering', models.BooleanField(default=False)),
                ('Rear_Suspension', models.BooleanField(default=False)),
                ('Front_Suspension', models.BooleanField(default=False)),
                ('Auto_Climate_Control', models.BooleanField(default=False)),
                ('Alloy_Wheels', models.BooleanField(default=False)),
                ('Power_Windows', models.BooleanField(default=False)),
                ('Air_Conditioner', models.BooleanField(default=False)),
                ('Passenger_Airbag', models.BooleanField(default=False)),
                ('Fog_Lights', models.BooleanField(default=False)),
                ('Heater', models.BooleanField(default=False)),
                ('Adjustable_Steering', models.BooleanField(default=False)),
                ('Air_Quality', models.BooleanField(default=False)),
                ('Remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeySpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Mileage', models.CharField(max_length=100)),
                ('Max_Power', models.CharField(max_length=100)),
                ('Transmission', models.CharField(max_length=100)),
                ('Seats', models.CharField(max_length=100)),
                ('Service_Cost', models.CharField(max_length=100)),
                ('Tank_Capacity', models.CharField(max_length=100)),
                ('Transmission_Type', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(max_length=100)),
                ('Engine_Displacement', models.CharField(max_length=100)),
                ('Body_Type', models.CharField(max_length=100)),
            ],
        ),
    ]
