# Generated by Django 2.2.4 on 2019-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_images_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp', models.CharField(max_length=100)),
                ('name', models.CharField(default='None', max_length=100)),
                ('Dis', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
