# Generated by Django 2.2.4 on 2019-11-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
    ]
