# Generated by Django 2.2.4 on 2019-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_remove_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyspecs',
            name='Body_Type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Engine_Displacement',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Fuel_Type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Max_Power',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Mileage',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Seats',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Service_Cost',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Tank_Capacity',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Transmission',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Transmission_Type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
