# Generated by Django 2.2.4 on 2019-11-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20191109_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyspecs',
            name='Transmission',
        ),
    ]
