# Generated by Django 2.2.4 on 2020-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_remove_keyspecs_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionscap',
            name='Height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dimensionscap',
            name='Width',
            field=models.CharField(max_length=100),
        ),
    ]
