# Generated by Django 2.2.4 on 2020-01-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200113_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('comp', models.CharField(default='None', max_length=100)),
                ('name', models.CharField(default='None', max_length=100)),
                ('price', models.IntegerField()),
                ('int_design', models.IntegerField()),
                ('ext_design', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('service_cost', models.IntegerField()),
                ('safety_score', models.IntegerField()),
                ('suggestion', models.TextField(max_length=250)),
            ],
        ),
    ]
