# Generated by Django 3.1.1 on 2020-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Body_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Engine_Displacement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Fuel_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Max_Power',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Mileage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Seats',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Service_Cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Tank_Capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='Transmission_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keyspecs',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
